name: Deploy to VM

on:
 push:
  branches:
    - master

jobs:
 deploy:
  runs-on: ubuntu-latest

 steps:
   - name: Checkout code
     uses: actions/checkout@v4
 
   - name: copy ssh into machine 
     run: |
      mkdir ~/.ssh
      cd ~/.ssh
      echo "${{ secrets.my_gcp_key}}" > my_gcp_key
      ls -ltr
      chmod 600 my_gcp_key
      ls -ltr
     
 
   - name: SSH into VM
     run: |
          ssh -i ~/.ssh/my_gcp_key -o StrictHostKeyChecking=no yashjain200502@35.246.23.173 << 'EOF'
            pwd
            ls -la
            echo "Successfully connected to VM"
          EOF
